### PR TITLE
Simplify platform requirements before 1.1

### LINKED ISSUE #675: Simplify automatic support of Unix-like platforms across modules
There are several places in TF-PSA-Crypto and Mbed TLS that have an adherence on non-standard C features, either mandatory or optional. We have built-in support for Unix-like platforms and for Windows, and sometimes ways to configure the library on other platforms. “Unix-like” covers a vast range of systems, including:

* Linux kernel with several possible libc.
* Unix implementations from a single vendor such as \*BSD, macOS, QNX, AIX, …
* Various Unix/POSIX/Linux layers on Windows.
* Various embedded systems with partial Unix APIs.

The goal of this issue is to simplify the code that we use to detect, and adapt to, Unix-like platforms, so that we are less afraid of breaking things if we need to fix a bug in the next long-time support branch. It covers both TF-PSA-Crypto and Mbed TLS.

Here are some known problems, as of TF-PSA-Crypto 1.0.0 and Mbed TLS 4.0.0:

* We include `unistd.h` and other Unix headers in many different places: [`platform_util.c`](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/tf-psa-crypto-1.0.0/drivers/builtin/src/platform_util.c#L149), [`threading.c`](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/tf-psa-crypto-1.0.0/drivers/builtin/src/threading.c#L26), [`unistd.c`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-4.0.0/library/timing.c#L16), [`net_sockets.c`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-4.0.0/library/net_sockets.c#L22) (and that's just for the library, the rest matters less). Each file has a different idea of whether to include QNX, Haiku, Midipix…
* Compiler options can break the build as they may influence which symbols are declared in system headers.
* We have hacks to allow a non-C99 `printf` [in `debug.h`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-4.0.0/include/mbedtls/debug.h#L90), only for Windows. These hacks may or may not work correctly because the `printf` variant (standard C99 or Windows legacy) is determined when `debug.c` is built, but the format strings is determined when `ssl_*.c` is built. They may end up being different if, for example, a module using debug also defines a macro such as `_POSIX_C_SOURCE` or `_XOPEN_SOURCE` — then Mingw will pull in the GNU printf implementation which is C99-compliant, instead of the default one which isn't. The way Mingw picks the printf implementation seems to have been overhauled in version 13, released in June 2025, and our code may not work with that version (I suspect that's the cause of https://github.com/Mbed-TLS/mbedtls/issues/10566). We've had other problems with these hacks before (https://github.com/Mbed-TLS/mbedtls/issues/10017).

Out of scope:

* Providing additional configurability is out of scope here. It is of course desirable, but it would take a lot of effort. This issue focusing on what works out of the box.
* Only the libraries is in scope. While it would be nice for the sample programs to run on more platforms, it's a lot less important. Test tools are completely out of scope, we only care about them running on our CI environment and on developer machines.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Resolve https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/675

* Rewrite `MBEDTLS_STATIC_ASSERT` and make it actually assert everywhere. This may work on extremely exotic C99-but-not-C11 compilers or compiler warnings.
* Move feature requirement macros that need to be defined before including any system header to a new dedicated header `core/tf_psa_crypto_platform_requirements.h`.
* Redo feature requirement macros from scratch, so that they're simpler and justified. This could cause “exotic” platforms to break.
* Always use C99-compliant printf on MingW, removing the need for `MBEDTLS_PRINTF_SIZET` in `debug.h`.
* Remove the use of `gettimeofday()` (we use `clock_gettime()` for `mbedtls_ms_time()`.

Needs preceding PR: 
* [x] [Stop using `gettimeofday()` in Mbed TLS](https://github.com/Mbed-TLS/mbedtls/pull/10607) (needed to fix the build on FreeBSD)
* [x] framework https://github.com/Mbed-TLS/mbedtls-framework/pull/279
* [x] Prepare mbedtls for the MingW change: https://github.com/Mbed-TLS/mbedtls/pull/10625

## PR checklist

- [x] **changelog** provided
- [x] **development PR** provided https://github.com/Mbed-TLS/mbedtls/pull/10606
- [x] **TF-PSA-Crypto PR** provided https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694
- [x] **framework PR** provided https://github.com/Mbed-TLS/mbedtls-framework/pull/279
- [x] **3.6 PR** https://github.com/Mbed-TLS/mbedtls/pull/10621 (only a small part that isn't disruptive)
- **tests**  provided + local testing (see https://github.com/Mbed-TLS/mbedtls/pull/10606)

### CODE REVIEW

File: core/tf_psa_crypto_common.h [hunk 1]
```diff
@@ -382,30 +382,121 @@ static inline void mbedtls_xor_no_simd(unsigned char *r,
...
- * For non GCC compilers we check that C>=11 is used since C11 introduced _Static_assert.
+
+#elif defined(_MSC_VER)
+/* MSVC has `static_assert` as a keyword (not a macro) since
+ * Visual Studio 2010.
+ */
+#define MBEDTLS_STATIC_ASSERT(expr, msg)    static_assert(expr, msg)
+
+#elif defined(__GNUC__) && \
+    ((__GNUC__ == 4 && __GNUC_MINOR >= 6) || __GNUC__ > 4) && \
```
Comment (bensze01) [inline core/tf_psa_crypto_common.h]: Preexisting typo
```suggestion
    ((__GNUC__ == 4 && __GNUC_MINOR__ >= 6) || __GNUC__ > 4) && \
```

**Review by bensze01 — CHANGES_REQUESTED** [review]

File: core/tf_psa_crypto_platform_requirements.h [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+ * where snprintf does not always zero-terminate the buffer, and does
+ * not support formats such as "%zu" for size_t and "%lld" for long long.
+ *
+ * Defining __USE_MINGW_ANSI_STDIO=0 may work and provide a small code size
+ * and performance benefit for some combinations of older Mingw and Windows
+ * versions. Do this at your own risk and make sure that least
+ * test_suite_platform_printf passes.
+ */
+#if !defined(__USE_MINGW_ANSI_STDIO)
+#define __USE_MINGW_ANSI_STDIO 1
```
Comment (gilles-peskine-arm) [inline core/tf_psa_crypto_platform_requirements.h:59]: I had missed that we need an extra step to avoid [breaking this branch of TF-PSA-Crypto with the current development branch of mbedtls](https://ci.trustedfirmware.org/job/mbed-tls-tf-psa-crypto-multibranch/job/PR-694-head/8/pipeline-console/log?nodeId=3388).

`mbedtls_common.h` includes `tf_psa_crypto_common.h` which now includes `tf_psa_crypto_platform_requirements.h‎` which defines `__USE_MINGW_ANSI_STDIO` causes `debug.c` to use a standard printf family. (That's in the default config. When `MBEDTLS_PLATFORM_VSNPRINTF_ALT` is enabled, what would matter is the printf family when `platform.c` is built.) This breaks the build in mbedtls since it's still assuming a legacy printf and setting `MBEDTLS_PRINTF_xxx` macros accordingly.

So I think that before merging this PR, we need to update mbedtls with the part of https://github.com/Mbed-TLS/mbedtls/pull/10606 that updates the MingW printf selection.

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_platform_requirements.h:59]: > When `MBEDTLS_PLATFORM_VSNPRINTF_ALT` is enabled, what would matter is the printf family when platform.c is built.

Ah, but we automatically enable `MBEDTLS_PLATFORM_VSNPRINTF_ALT` (and `MBEDTLS_PLATFORM_SNPRINTF_ALT` but not the others) on MingW (and older, unsupported MSVC). Things can never be simple, can they?

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_platform_requirements.h:59]: https://github.com/Mbed-TLS/mbedtls/pull/10625

File: core/tf_psa_crypto_common.h [hunk 3]
```diff
@@ -382,30 +382,121 @@ static inline void mbedtls_xor_no_simd(unsigned char *r,
...
+ * - Chibicc 2020-12-07 ignores the assertion.
+ * - LC3 (trunk) ignores the assertion.
+ * - ppci 0.5.5 dies with a NotImplementedError on the `!` operator.
+ * - SDCC 4.0.0 through 4.5.0 complains if there are multiple assertions in
+ *   the same scope:
+ *   "extern definition for 'mbedtls_static_assert_anchor' mismatches with declaration."
+ */
 #define MBEDTLS_STATIC_ASSERT(expr, msg)                                \
-    struct ISO_C_does_not_allow_extra_semicolon_outside_of_a_function
+    extern void mbedtls_static_assert_anchor(char[(expr) ? 1 : -1])
```
Comment (bensze01) [inline core/tf_psa_crypto_common.h]: This expression doesn't assert if `expr` is not an integer-constant expression - eg. when running `gcc` with `-std=c99`. See:
https://godbolt.org/z/jKz48nTPh

Instead, we should use a statement derived from the current version of `STATIC_ASSERT_EXPR`, which is also fully valid C99:
https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/20f2ca9dd2ffd1516fa62b4c0eff32a292048974/core/tf_psa_crypto_common.h#L82-L85

```suggestion
    struct mbedtls_static_assert_anchor { int MBEDTLS_STATIC_ASSERT : (expr) ? 1 : -1; }
```

File: core/tf_psa_crypto_common.h [hunk 4]
```diff
@@ -382,30 +382,121 @@ static inline void mbedtls_xor_no_simd(unsigned char *r,
...
+#elif defined(__COUNTER__)
+/* Fall back to a hack that works in practice with non-ancient GCC-like
+ * compilers and MSVC, and doesn't trigger `-Wredundant-decls`.
+ *
+ * See the `#else` block below for an explanation. Here, we add another
+ * layer to make the declared name unique using the special preprocessor
+ * token `__COUNTER__`.
+ */
+#define MBEDTLS_STATIC_ASSERT_COUNTER(expr, counter) \
+    extern void mbedtls_static_assert_anchor##counter(char[1 - 2 * !(expr)])
```
Comment (bensze01) [inline core/tf_psa_crypto_common.h]: The integer constant expression here doesn't match the non-counter version below.

I assume the intent was to standardize on either  the arithmetic or the ternary expression - the ternary seems to be easier to parse for users when presented as an error message, so I'd prefer that one if there are no compatibility implications (both should be fully C99 compliant).

Also see: https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694#discussion_r2865507542

```suggestion
    struct mbedtls_static_assert_anchor##counter { int MBEDTLS_STATIC_ASSERT : (expr) ? 1 : -1; }
```

File: tests/suites/test_suite_platform_unix.function [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+/* END_CASE */
+
+/* BEGIN_CASE depends_on:MBEDTLS_PLATFORM_IS_UNIXLIKE */
+void clock_gettime_available(int clockid)
+{
+    struct timespec ts = { 0, 0 };
+    memset(&ts, 0, sizeof(ts));
+    int ret = clock_gettime(clockid, &ts);
+    TEST_ASSERT_ERRNO(ret == 0);
+    TEST_LE_S(1, ts.tv_sec);
```
Comment (bensze01) [inline tests/suites/test_suite_platform_unix.function]: This will fail if the system clock is set to a value <= 1970-01-01T00:00:00 if `time_t` is signed :)

I think we can just remove this check, since we don't care about a functional realtime clock.

If we care about the clock being functional, we could test that `(ts.tv_sec | ts.tv_nsec) != 0`, which should cut down the probability to near zero, or assert that a second call to `clock_gettime` (after a short sleep)  doesn't return the same values.

File: tests/suites/test_suite_platform_unix.function [hunk 6]
```diff
@@ -17,8 +17,12 @@
...
 
 /* Constants used in the test data need to be defined even if no test
- * functions that use them are enabled. */
+ * functions that use them are enabled.
+ * Undefine the macros first in case a system header does define them
+ * even though we haven't recognized the platform as Unix-like. */
+#undef CLOCK_REALTIME
 #define CLOCK_REALTIME 0
+#undef CLOCK_MONOTONIC
 #define CLOCK_MONOTONIC 0
```
Comment (bensze01) [inline tests/suites/test_suite_platform_unix.function:26]: Redefining system macros feels like it might bite us in the future.

Why not just wrap the definitions with `#if !defined(FOO)` ?

File: core/tf_psa_crypto_common.h [hunk 7]
```diff
@@ -104,7 +104,7 @@ extern void (*mbedtls_test_hook_test_fail)(const char *test, int line, const cha
 /* A compile-time constant with the value 0. If `const_expr` is not a
  * compile-time constant with a nonzero value, cause a compile-time error. */
 #define STATIC_ASSERT_EXPR(const_expr)                                \
-    (0 && sizeof(struct { unsigned int STATIC_ASSERT : 1 - 2 * !(const_expr); }))
+    (0 && sizeof(char[1 - 2 * !(const_expr)]))
```
Comment (bensze01) [inline core/tf_psa_crypto_common.h]: What version of GCC complains about anonymous structs?

I could only find a commit message (c86a16548c82c345d2784d6b79eecfcef71ce08a) that claimed MSVC was unhappy - if GCC is happy with the original definition, then in light of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694#discussion_r2865507542 I don't see any clear benefit from this patch.

On a second note, my suggestion in https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694#discussion_r2865507542 doesn't use anonymous structs, so MSVC should be happy as well - either that approach, or a [__pragma](https://learn.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=msvc-170#the-pragma-keyword) could be used to silence the specific warning on MSVC.

**Review by bensze01 — CHANGES_REQUESTED** [review]

File: core/tf_psa_crypto_common.h (hunk 7 above)
Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: I couldn't get a struct to work when `STATIC_ASSERT_EXPR` is used inside of `ARRAY_LENGTH` which is used in `MBEDTLS_STATIC_ASSERT` (which we do in our code base, that's how I noticed), when `MBEDTLS_STATIC_ASSERT` is implemented in a way that doesn't rely on anything but C99. See the commit message for d5e30685a045bdf30c210d1d1d47151452207fe6.

If the struct is named then you can't have two assertions in the same scope. If the struct is not named then GCC complains that an anonymous struct in a “small” scope is silly.

File: core/tf_psa_crypto_common.h (hunk 3 above)
Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: Same as https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694#discussion_r2867415042 : I ddn't manage to get a struct to work. With your proposal, you can't have two assertions in the same scope.

File: core/tf_psa_crypto_common.h (hunk 4 above)
Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: I'll need to go back and check, but IIRC on Godbolt I found a compiler that treated `array[(0) ? 1 : -1]` as a VLA but produced a compilation error with `array[1 - 2 * (0)]`.

File: tests/suites/test_suite_platform_unix.function (hunk 5 above)
Comment (gilles-peskine-arm) [reply tests/suites/test_suite_platform_unix.function]: I don't want to check that `clock_gettime()` is functional, but I would like to check that it's actually returning something that isn't all-bits-zero.

Indeed calling the function twice with a delay in between would be a better test, but I also don't want to make assumptions on delays. That tends to play badly in the CI.

I think just checking that the return value isn't all-bits-zero is indeed better. Not because I'm worried about the epoch, but because `clock_gettime` can have different clocks, including one that starts at boot, and running the test less than 1 second after boot is plausible.

File: tests/suites/test_suite_platform_unix.function (hunk 6 above)
Comment (gilles-peskine-arm) [reply tests/suites/test_suite_platform_unix.function:26]: This is only in the case where we believe that the platform isn't Unix-like, but system headers have defined these macros anyway. The definitions provided by system headers might not work either.

This could be solved with a level of indirection (use `MBEDTLS_TEST_CLOCK_REALTIME` in test data and define it differently depending on `MBEDTLS_PLATFORM_IS_UNIXLIKE`), but I don't think this warrants the additional complexity. These macro redefinitions are only done in a case where there's very little code in the `.c` file after them (since none of the test functions are compiled in).

File: core/tf_psa_crypto_common.h (hunk 3 above)
Comment (yanesca) [inline core/tf_psa_crypto_common.h]: Based on your [previous comment](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/694/changes/9ebf182ca45680137027ff93c95812b1665d9996#r2867417298
) some compilers would treat this as a VLA and wouldn't fail. Is this not a problem?

(This is just a random question, I am not doing a full review.)

**Review by valeriosetti — DISMISSED** [review]

File: core/tf_psa_crypto_common.h (hunk 7 above)
Comment (bensze01) [reply core/tf_psa_crypto_common.h]: I see - that's annoying. How would you feel about keeping the struct-based approach I suggested if `__COUNTER__` is available, and going with the array-length-based approach if it is not available?

File: core/tf_psa_crypto_common.h (hunk 3 above)
Comment (bensze01) [reply core/tf_psa_crypto_common.h]: I think I managed to combine our approaches in a way that avoids false-negatives via misinterpretation as a VLA, and is accepted by old versions of GCC without warnings:

```suggestion
    extern void mbedtls_static_assert_anchor(char[sizeof(struct {int MBEDTLS_STATIC_ASSERT : 1 - 2 * !(expr);} )])
```

Comment (bensze01) [reply core/tf_psa_crypto_common.h]: ~~Whelp - it works in GCC, but ICC just ignores the violation inside the `sizeof` :(~~

Comment (bensze01) [reply core/tf_psa_crypto_common.h]: Nope, ICC handles this correctly, I was just testing it wrong.

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: That doesn't work, see the commit message for d5e30685a045bdf30c210d1d1d47151452207fe6.

However, I may have been too focused on declaring a function.
```
extern int mbedtls_static_assert_anchor[sizeof(struct {int x : (expr) ? 1 : -1;})]
```
is looking promising so far. I still need to check more compilers.

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: No, I did have a reason for declaring a function: if it's not a function, then in function scope, this is likely to cause an unused-variable warning. I can pretty much universally silence that warning with `(void) mbedtls_static_assert_anchor`, but that only works in function scope, not at file scope.

Maybe the right way to do this would be to have different macros, one for file scope and one for function scope?

I'm going to try a little more, but at some point I propose that we merge what we have, and improve it later. Before this pull request, `MBEDTLS_STATIC_ASSERT` was a no-op on compilers that were neither C11 nor GCC-like. So it's still an improvement over the existing situation if we now cover most common compilers that are neither C11 nor GCC-like.

----

By the way

> This expression doesn't assert if expr is not an integer-constant expression

is not a critical problem. We run builds where `MBEDTLS_STATIC_ASSERT` is a C11 static assert, and that will fail the build if `expr` is not a constant expression. The only way a problem would be unnoticed is if `expr` involes some user configuration or platform-dependent macro, and that macro is not a constant expression in some real-world usage, but it is a constant expression in all of our CI builds, and that macro is not used in any other place where a constant expression is required. It's better if we detect this, but it's fairly unlikely to happen.

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: A function _returning_ a pointer to an array might avoid both pitfalls: compilers don't usually complain about an unused function declaration even at function scope, and they don't seem to complain about an anonymous struct inside an array length.

```
#define MBEDTLS_STATIC_ASSERT(expr, msg)                                \
    extern int (*mbedtls_static_assert_anchor(void))[sizeof(struct {int x : (expr) ? 1 : -1;})]
```

This is actually something I found online, but IIRC I had a reason against it as well. I don't recall what that reason was though, so I'm going to try it out some more.

Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: The only serious problem I can find with a function returning a pointer to an array whose size involves a struct with a potentially negative bit-field width (other than its complexity) is that MSVC doesn't like it. But fortunately we have a different implementation with (non-ancient) MSVC.

File: core/tf_psa_crypto_common.h (hunk 7 above)
Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: At least up to version 15.1.0, GCC doesn't seem to complain about an anonymous struct inside sizeof inside an array that is not in a function argument list. So I've switched to that.

File: core/tf_psa_crypto_common.h (hunk 4 above)
Comment (gilles-peskine-arm) [reply core/tf_psa_crypto_common.h]: Moot since I've now moved everything to a bit-field width.

File: tests/suites/test_suite_platform_unix.function (hunk 6 above)
Comment (gilles-peskine-arm) [reply tests/suites/test_suite_platform_unix.function:26]: I don't intend to change this. Neither of  the proposed simple solutions is 100% correct, and both are highly unlikely to fail in practice, so I think they're equally fine.

**Review by bensze01 — DISMISSED** [review]
Thanks, LGTM - needs a rebase due to a submodule conflict.

**Comment by gilles-peskine-arm** [comment]
I've rebased on top of `development`. The framework is already up to date there, so the framework updates have been dropped. No other change.

**Review by valeriosetti — APPROVED** [review]

**Review by bensze01 — APPROVED** [review]
