### PR TITLE
Stop defining inline in our headers

### LINKED ISSUE #662: Stop defining inline in our headers
We [define `inline` as a macro on ArmCC and MSVC](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/tf-psa-crypto-1.0.0/include/tf-psa-crypto/build_info.h#L98).

We no longer officially support ArmCC 5, which is a C90 compiler (although it has enough C99 features that it still works for most of our code — I think the main exception is some Arm-specific optimizations which don't compile anymore). We no longer support older versions of MSVC where `inline` wasn't a keyword (we dropped Visual Studio 2010 when we made C99 an official requirement, and in 3.6 we document VS 2017 as the minimum version; my reading of [MSVC documentation](https://learn.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-140) is that `inline` is a keyword at least as far back as VS 2015). So these definitions of `inline` should not be needed any longer.

It's a bit rude to define this in a header that application code will include, even if we only do it on specific compilers where it should be ok. It's true that we've been doing it for a very long time without complaints (in `build_info.h` since Mbed TLS 3.0, and in some public headers since PolarSSL 0.99+). But it has caused a problem recently: [it broke the build of mldsa-native](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/655#issuecomment-3752488047). So I think we should remove it. If someone really wants to make the library work on a compiler that doesn't have a full C99 including the `inline` keyword, they can define the macro themselves.

This is a trivial change in terms of code difference, but not in terms of implications, so I don't want to do it in an LTS branch.

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

Resolves #662

## PR checklist

- [ ] **changelog** provided
- [ ] **framework PR** not required
- [ ] **mbedtls development PR** not required because: no change there
- [ ] **mbedtls 3.6 PR** not required because: no backport
- **tests**  not required because: no code change

### CODE REVIEW

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

Although, should we have a changelog entry, since this removes some practical portability? This doesn't remove theoretical portability since it only affects compilers that we officially don't support (ArmCC 5, old MSVC).

**Comment by valeriosetti** [comment]
> Although, should we have a changelog entry, since this removes some practical portability? This doesn't remove theoretical portability since it only affects compilers that we officially don't support (ArmCC 5, old MSVC).

Yeah, indeed this was the question I raised in the description of the PR. TBH I don't know: if you or the 2nd reviewer think it's better to have a ChangeLog, I will add it :)

**Comment by hoffbrinkle** [comment]
I would recommend one. It's a macro in a header file so it could have some "spooky action at distance." If someone is trying to figure out why their build is behaving differently, this could valuable to figure that out.

**Comment by valeriosetti** [comment]
> I would recommend one. It's a macro in a header file so it could have some "spooky action at distance." If someone is trying to figure out why their build is behaving differently, this could valuable to figure that out.

Done ;)

**Review by bjwtaylor — DISMISSED** [review]

File: ChangeLog.d/issue662.txt [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Removals
+   * Definition of macro 'inline' is removed from 'build_info.h'. This was
+     used on some old non-C99-compliant compilers (ArmCC 5 and old MSVC) for
+     which support for building the library has already been dropped in the
+     past.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/issue662.txt]: Suggested minor English improvements:

> The headers no longer define 'inline' as a macro. This was done on Arm Compiler 5 and MSVC. The compiler versions that needed this definition are no longer supported since TF-PSA-Crypto 1.0.

**Comment by gilles-peskine-arm** [comment]
> It's a macro in a header file so it could have some "spooky action at distance."

Indeed, such spooky action when including both our headers and another library is [why defining the macro was a problem](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/655#issuecomment-3752488047). I can imagine weirdness in the other direction as well.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by bjwtaylor — APPROVED** [review]
